#pragma once

// Ampli Onkyo
extern uint16_t SMARTHOME_MQTT_AMPLI_POWER_TOGGLE;      
extern uint16_t SMARTHOME_MQTT_AMPLI_POWER_ON;      
extern uint16_t SMARTHOME_MQTT_AMPLI_POWER_OFF;     
extern uint16_t SMARTHOME_MQTT_AMPLI_INPUT_BD_DVD;      
extern uint16_t SMARTHOME_MQTT_AMPLI_INPUT_CBL_SAT;     
extern uint16_t SMARTHOME_MQTT_AMPLI_INPUT_STB_DVR;     
extern uint16_t SMARTHOME_MQTT_AMPLI_INPUT_GAME;        
extern uint16_t SMARTHOME_MQTT_AMPLI_INPUT_PC;      
extern uint16_t SMARTHOME_MQTT_AMPLI_INPUT_AUX;     
extern uint16_t SMARTHOME_MQTT_AMPLI_INPUT_TV_CD;       
extern uint16_t SMARTHOME_MQTT_AMPLI_VOL_UP;       
extern uint16_t SMARTHOME_MQTT_AMPLI_VOL_DOWN;        
extern uint16_t SMARTHOME_MQTT_AMPLI_MUTE;       
extern uint16_t SMARTHOME_MQTT_AMPLI_BASS_UP;       
extern uint16_t SMARTHOME_MQTT_AMPLI_BASS_DOWN;     
extern uint16_t SMARTHOME_MQTT_AMPLI_TREBLE_UP;       
extern uint16_t SMARTHOME_MQTT_AMPLI_TREBLE_DOWN;          
extern uint16_t SMARTHOME_MQTT_AMPLI_MODE_MOVIE;       
extern uint16_t SMARTHOME_MQTT_AMPLI_MODE_MUSIC;       
extern uint16_t SMARTHOME_MQTT_AMPLI_MODE_GAME;    
extern uint16_t SMARTHOME_MQTT_AMPLI_INFO;               

// TV LG
extern uint16_t SMARTHOME_MQTT_TV_POWER_OFF;
extern uint16_t SMARTHOME_MQTT_TV_POWER_ON;
extern uint16_t SMARTHOME_MQTT_TV_POWER_TOGGLE;
extern uint16_t SMARTHOME_MQTT_TV_SOURCE;
extern uint16_t SMARTHOME_MQTT_TV_CHANNEL_UP;
extern uint16_t SMARTHOME_MQTT_TV_CHANNEL_DOWN;
extern uint16_t SMARTHOME_MQTT_TV_MENU;
extern uint16_t SMARTHOME_MQTT_TV_GUIDE;
extern uint16_t SMARTHOME_MQTT_TV_SETUP;
extern uint16_t SMARTHOME_MQTT_TV_INFO;
extern uint16_t SMARTHOME_MQTT_TV_UP;
extern uint16_t SMARTHOME_MQTT_TV_DOWN;
extern uint16_t SMARTHOME_MQTT_TV_LEFT;
extern uint16_t SMARTHOME_MQTT_TV_RIGHT;
extern uint16_t SMARTHOME_MQTT_TV_OK;
extern uint16_t SMARTHOME_MQTT_TV_RETURN;
extern uint16_t SMARTHOME_MQTT_TV_EXIT;
extern uint16_t SMARTHOME_MQTT_TV_KEY_A;
extern uint16_t SMARTHOME_MQTT_TV_KEY_B;
extern uint16_t SMARTHOME_MQTT_TV_KEY_C;
extern uint16_t SMARTHOME_MQTT_TV_KEY_D;
extern uint16_t SMARTHOME_MQTT_TV_INPUT_HDMI_1;
extern uint16_t SMARTHOME_MQTT_TV_INPUT_HDMI_2;
extern uint16_t SMARTHOME_MQTT_TV_INPUT_HDMI_3;
extern uint16_t SMARTHOME_MQTT_TV_INPUT_HDMI_4;
extern uint16_t SMARTHOME_MQTT_TV_INPUT_TV;
extern uint16_t SMARTHOME_MQTT_TV_HOME;
       
// nVIDIA SHIELD
extern uint16_t SMARTHOME_MQTT_SHIELD_POWER_TOGGLE;
extern uint16_t SMARTHOME_MQTT_SHIELD_MENU;
extern uint16_t SMARTHOME_MQTT_SHIELD_EXIT;
extern uint16_t SMARTHOME_MQTT_SHIELD_STOP;
extern uint16_t SMARTHOME_MQTT_SHIELD_PLAY;
extern uint16_t SMARTHOME_MQTT_SHIELD_FORWARD;
extern uint16_t SMARTHOME_MQTT_SHIELD_REVERSE;
extern uint16_t SMARTHOME_MQTT_SHIELD_UP;
extern uint16_t SMARTHOME_MQTT_SHIELD_DOWN;
extern uint16_t SMARTHOME_MQTT_SHIELD_LEFT;
extern uint16_t SMARTHOME_MQTT_SHIELD_RIGHT;
extern uint16_t SMARTHOME_MQTT_SHIELD_OK;
extern uint16_t SMARTHOME_MQTT_SHIELD_SHIELD;

// HomeAssistant
extern uint16_t SMARTHOME_MQTT_HA_LABOULE_SET;
extern uint16_t SMARTHOME_MQTT_HA_LABOULE_TOGGLE;
extern uint16_t SMARTHOME_MQTT_HA_LABOULE_BRIGHTNESS_SET;
extern uint16_t SMARTHOME_MQTT_HA_PLAFOND_SET;
extern uint16_t SMARTHOME_MQTT_HA_PLAFOND_TOGGLE;
extern uint16_t SMARTHOME_MQTT_HA_PLAFOND_BRIGHTNESS_SET;
extern uint16_t SMARTHOME_MQTT_HA_PLAFOND2_SET;
extern uint16_t SMARTHOME_MQTT_HA_PLAFOND2_BRIGHTNESS_SET;
extern uint16_t SMARTHOME_MQTT_HA_PIXAR_SET;
extern uint16_t SMARTHOME_MQTT_HA_PIXAR_BRIGHTNESS_SET;
extern uint16_t SMARTHOME_MQTT_HA_NANOLEAF_SET;
extern uint16_t SMARTHOME_MQTT_HA_NANOLEAF_BRIGHTNESS_SET;

void register_device_smarthome();
